# Trained using GTX-1080ti x4. It takes about 1days.
batch_type: folded
batch_size: 32
accum_grad: 8
max_epoch: 100
patience: none

# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 2048
    num_blocks: 5
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

model_conf:
    input_size: 50000
    length_normalized_loss: false

optim: adam
optim_conf:
    lr: 0.005
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 30000

normalize: utterance_mvn
normalize_conf:
    norm_means: true
    norm_vars: false
    eps: 1.0e-20

rir_scp: data/reverb_rir_single/wav.scp
noise_scp: data/reverb_noise_single/wav.scp
speech_volume_normalize: 1.
noise_db_range: "12_17"
rir_apply_prob: 1.
noise_apply_prob: 1.
